# Generated by Django 5.1.2 on 2024-12-17 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_exercises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('score', models.IntegerField(default=3)),
                ('comment', models.TextField(max_length=1000, null=True)),
                ('date', models.DateField(null=True)),
                ('signature', models.CharField(default='Firma', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='score',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
